import socket
print(socket.gethostbyname('www.iitism.ac.in'))
#print(socket.gethostname())
#print(socket.getservbyname('ssh', 'tcp'))
#print(socket.getservbyname('http','tcp'))
#print(socket.getservbyname('ftp','tcp'))
#transport layered protocols
# print(socket.getprotobyname('tcp'))
# print(socket.getprotobyname('udp'))
# print(socket.getprotobyname('igmp'))
# print(socket.getprotobyname('icmp'))
# print(socket.getprotobyname('ospf'))
#print(socket.gethostbyname_ex('www.iitism.ac.in'))
#print(socket.getfqdn('www.iitism.ac.in'))
#print(socket.gethostbyaddr('49.50.109.66'))
#print(socket.gethostbyaddr('8.8.8.8'))
# print(socket.getservbyname('http'))
# print(socket.getservbyname('smtp','tcp'))
# print(socket.getservbyname('ftp'))
# print(socket.getservbyname('ssh'))
# print(socket.getservbyport(80))
# print(socket.getservbyport(22))
#print(socket.getservbyport(21,'tcp'))
# print(socket.getservbyport(1))
# print(socket.getservbyport(6))
# print(socket.getservbyport(25))
#print(socket.getservbyport(23))
